#server:
#  port: 8080
#  servlet:
#    context-path: /wsserver


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wsserver?characterEncoding=utf8
    username: root
    password: zxc123zxc


