#server:
#  port: 8080
#  servlet:
#    context-path: /wsserver


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://db4free.net:3306/keling?characterEncoding=utf8
    username: keling
    password: zxc123zxc
    tomcat:
      max-active: 20
      initial-size: 1
      max-wait: 60000


