server:
  port: 8080
  servlet:
    context-path: /chathub




spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.133:3306/wsserver?characterEncoding=utf8
    username: root
    password: zxc123zxc
  output:
    ansi:
      enabled: detect


logging:
  file: ./logs/core.log
  level:
    ROOT: info





