server:
  port: 8082


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ws?characterEncoding=utf8
    password: root
    username: root
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    filter: stat,wall.log4j


